### ISSUE TITLE
Underfitting problem

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [DeepVoltaire/AutoAugment#10]
When I used auto augment with my custom NN arch with CIFAR-10 dataset, I got more testing accuracy and less training accuracy. I tried many things and it happens when I implement autoaugmentation only, the under fitting problem, Can please explain why this happening?
Just looking for answers...

**Comment by DeepVoltaire** [comment]
Data augmentation is changing the images you show your network by distorting and moving the images around in all kinds of ways. This makes it harder to overfit and if your model has not enough complexity it can also result in underfitting. So this is perfectly normal and if you want to move out of this underfitting situation you should increase the complexity of your model or use less aggressive data augmentation.
