### ISSUE TITLE
Unexpected keyword argument 'fillcolor' when running demo code

### ISSUE THREAD

**Issue by HelaiBAI97** [DeepVoltaire/AutoAugment#14]
When I test the demo AutoAugment_Exploration.ipynb, I always get the same error: "TypeError: transform() got an unexpected keyword argument 'fillcolor'". Anyone knows why this happens?

**Comment by horacejlee** [comment]
I think the `fillcolor` argument for `Image.transform()` is only supported in Pillow>=5.0.0 so try upgrading your version of Pillow if it's below 5.0.0.

**Comment by DeepVoltaire** [comment]
Exactly, thanks @horacejlee. Upgrade Pillow with "pip install Pillow -U".
