### ISSUE TITLE
best sub-policies?

### ISSUE THREAD

**Issue by zihaozhang9** [DeepVoltaire/AutoAugment#15]
In autoaugment.py.
best Sub-policies.How to determine the parameters.Do these parameters also use my own data?

**Comment by DeepVoltaire** [comment]
The best Sub-policies with their best parameters were found for specific datasets, e.g. ImageNet or SVHN, in the paper. To find the best Sub-policies for your dataset you would need to find and run an implementation of the search algorithm the authors used.
