### ISSUE TITLE
Pretrained imagenet models?

### ISSUE THREAD

**Issue by rtaori** [DeepVoltaire/AutoAugment#18]
Hi,

Would it be possible to release the pretrained imagenet autoaugment models? In particular, the resnet50 one would be very helpful. I am looking to use it for further downstream work.

thanks

**Comment by DeepVoltaire** [comment]
I would ask the authors of AutoAugment for releasing them. They have released their code for training CIFAR10/CIFAR100 with the best AutoAugment policies [here](https://github.com/tensorflow/models/tree/master/research/autoaugment). At the bottom of the link are their contact details for further inquiries.
