### ISSUE TITLE
Hi, why do you divide the magnitude of `translate operation` by 331?

### ISSUE THREAD

**Issue by CoinCheung** [DeepVoltaire/AutoAugment#19]
Hi, 

Thanks a lot for your kindly publishing the code base !!

https://github.com/DeepVoltaire/AutoAugment/blob/d708e2125cf71a4c08a101e55e5cc569521ffe50/autoaugment.py#L177

I noticed that, in this line, the magnitude of translate operation is divided by 331. Would you please tell me the reason you implement this? 

By the way, is the meanings of the magnitudes and their explanations in the paper of [learning augs for object detection](https://arxiv.org/abs/1906.11172) the same as in this paper? Could I simply modify the combination of the policies in this codebase to implement the augmentation method proposed in that paper?

I am looking for your generous guidance :)

**Comment by DeepVoltaire** [comment]
Hi,

good questions! :)
The AutoAugment authors note in table 7 in the appendix that they have applied the augmentations on 331x331 images. So, if I want to calculate the translation magnitude in percentage points I divide the translation magnitude 150 by the image size 331.

I did not know of that paper yet, thanks! This looks very similar, SolarizeAdd and "BBox Only X" are new. You would need to change not only the image, but also the bounding boxes while transforming. But this repository is a good start to do just that.
