### ISSUE TITLE
[Bug] Missing random.choice in rotate

### ISSUE THREAD

**Issue by LXXXXR** [DeepVoltaire/AutoAugment#28]
Hi,
Thank you for the wonderful work!
Just wanna share a tiny concern. It seems to me that here the `magitude` should be `magnitude * random.choice([-1, 1]`, otherwise the rotate will always be in one direction. 
https://github.com/DeepVoltaire/AutoAugment/blob/17d718251f25c0d9413bf30f91b523907924f33a/autoaugment.py#L208
Thank you.

**Comment by DeepVoltaire** [comment]
Thank you for reporting the bug!
