### ISSUE TITLE
The autocontrast operation may have some problem.

### ISSUE THREAD

**Issue by Xthkeer** [DeepVoltaire/AutoAugment#6]
I noticed that the autocontrast operation didn't fill in the cutoff parameter. Is this normal? Without this parameter, it can only make a small change to the picture.

https://github.com/DeepVoltaire/AutoAugment/blob/1002a40c90ae8b22e05afb51831161fbb9a6c505/autoaugment.py#L218

**Comment by DeepVoltaire** [comment]
In the appendix of the AutoAugment paper they describe the autocontrast operation as "Maximize the the image contrast, by making the darkest pixel black and lightest pixel white." and do not give any parameter values for the cutoff. This means autocontrast is not used with a cutoff.
