### ISSUE TITLE
fill parameter does not exist for RandomCrop and cifar10

### ISSUE THREAD

**Issue by ahundt** [DeepVoltaire/AutoAugment#8]
The readme says the following for RandomCrop with cifar10:

```
 [transforms.RandomCrop(32, padding=4, fill=128), # gray fill value is important bc of the color operations
```

However, [torchvision.transforms.RandomCrop(size, padding=0, pad_if_needed=False)](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomCrop) does not support fill as a valid parameter.

**Comment by DeepVoltaire** [comment]
The documentation following your link shows the fill parameter, but it seems that the current pip version does not have this parameter yet. Installing torchvision from source shows me the fill parameter. I add this note to the README thank you!
